openapi: 3.0.4
info:
  title: Track-POD Address VehicleCheck API
  description: 'Track-POD API enables ERP or any other system integration with Track-POD without need for any manual data input. Our API provides an easy HTTP interface to Track-POD functionality through JSON or XML<br><br><b>Endpoint:</b><br>https://api.track-pod.com/<br><br><b>Request headers:</b><br><b>X-API-KEY</b> - API Key. Please find the API key in the Track-POD settings <br><b>Content-Type</b> - (POST/PUT) Request input type: <b>application/json</b> - JSON, <b>application/xml</b> - XML<br><b>Accept</b> - Response output type: <b>application/json</b> - JSON, <b>application/xml</b> - XML <br><b>Accept-Encoding</b> - Response compression: <b>gzip, deflate, br</b><br><br><b>Webhooks:</b><br>Create/Update/Delete route, Create/Update/Delete order, and more <a target=''_blank'' href=''https://track-pod.freshdesk.com/support/solutions/articles/103000049842''>How to use Webhooks?</a>'
  version: '2.0'
security:
- ApiKey: []
tags:
- name: VehicleCheck
paths:
  /VehicleCheck/{number}:
    get:
      tags:
      - VehicleCheck
      summary: Get last vehicle check by number
      operationId: GetCheckByVehicle
      parameters:
      - name: number
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Vehicle check
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/VehicleCheck'
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleCheck'
            text/json:
              schema:
                $ref: '#/components/schemas/VehicleCheck'
            application/xml:
              schema:
                $ref: '#/components/schemas/VehicleCheck'
            text/xml:
              schema:
                $ref: '#/components/schemas/VehicleCheck'
        '401':
          description: Unauthorized. Invalid X-API-KEY in the request header
        '429':
          description: Too Many Requests. Rate limit is 20 requests/sec and 400 requests/min
        '500':
          description: Internal Server Error
  /VehicleCheck/Number/{number}/Date/{date}:
    get:
      tags:
      - VehicleCheck
      summary: Get vehicle checks by date
      operationId: GetChecksByVehicle
      parameters:
      - name: number
        in: path
        required: true
        schema:
          type: string
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Vehicle checks
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            text/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
        '401':
          description: Unauthorized. Invalid X-API-KEY in the request header
        '429':
          description: Too Many Requests. Rate limit is 20 requests/sec and 400 requests/min
        '500':
          description: Internal Server Error
  /VehicleCheck/Date/{date}:
    get:
      tags:
      - VehicleCheck
      summary: Get vehicle checks by date
      operationId: GetVehicleChecksByDate
      parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Vehicle checks
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            text/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
        '401':
          description: Unauthorized. Invalid X-API-KEY in the request header
        '429':
          description: Too Many Requests. Rate limit is 20 requests/sec and 400 requests/min
        '500':
          description: Internal Server Error
components:
  schemas:
    VehicleCheckStage:
      enum:
      - BeforeRoute
      - AfterRoute
      type: string
    VehicleCheck:
      type: object
      properties:
        DriverLogin:
          type: string
          description: Driver's login
          nullable: true
          example: 'RT567 '
        DriverName:
          type: string
          description: Driver’s First Name and Last Name
          nullable: true
          example: Peter G.
        DepotId:
          type: string
          description: Unique identifier in user accounting system
          nullable: true
          example: 1
        Depot:
          type: string
          description: Depot address
          nullable: true
          example: '9 Riverside, Salford M7 1PA '
        Date:
          type: string
          format: date-time
        VehicleNumber:
          type: string
          description: Vehicle number
          nullable: true
          example: XXX777
        Odometer:
          type: number
          description: Odometer
          format: double
          nullable: true
        Values:
          type: array
          items:
            $ref: '#/components/schemas/VehicleCheckValue'
          description: Vehicle check values
          nullable: true
          xml:
            name: Values
            wrapped: true
        HasSignature:
          type: boolean
          description: Signature attached
          example: true
        SignaturePhoto:
          type: string
          description: Links for download jpg file (each link is available for 24h from API call)
          nullable: true
        Stage:
          $ref: '#/components/schemas/VehicleCheckStage'
        RouteNumber:
          type: string
          nullable: true
      additionalProperties: false
      xml:
        name: VehicleCheck
    VehicleCheckValue:
      type: object
      properties:
        Label:
          type: string
          description: Vehicle check label
          nullable: true
          example: Tyre and Wheel Nuts
        Status:
          type: boolean
          description: Check status
          nullable: true
        Photo:
          type: boolean
          description: Photo attached
          nullable: true
        Photos:
          type: array
          items:
            type: string
          description: Array of links for download jpg file (each link is available for 24h from API call)
          nullable: true
          xml:
            name: Photos
          example:
          - https://image.track-pod.com/...
        Note:
          type: string
          description: Note
          nullable: true
        Value:
          type: number
          description: Value
          format: double
          nullable: true
      additionalProperties: false
      xml:
        name: VehicleCheckValue
  securitySchemes:
    ApiKey:
      type: apiKey
      description: Please enter API key into field
      name: X-API-KEY
      in: header
