openapi: 3.2.0
info:
  title: Track-POD Reject Reason API
  description: Track-POD API enables ERP or any other system integration with Track-POD without need for any manual data input.
  version: '2.0'
security:
- ApiKey: []
tags:
- name: Reject Reason
paths:
  /RejectReason:
    get:
      tags:
      - Reject Reason
      summary: Get reasons for rejection list
      operationId: GetRejectReasonsList
      responses:
        '200':
          description: A reasons for rejection list
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RejectReasonsList'
            application/json:
              schema:
                $ref: '#/components/schemas/RejectReasonsList'
            text/json:
              schema:
                $ref: '#/components/schemas/RejectReasonsList'
            application/xml:
              schema:
                $ref: '#/components/schemas/RejectReasonsList'
            text/xml:
              schema:
                $ref: '#/components/schemas/RejectReasonsList'
        '401':
          description: Unauthorized. Invalid X-API-KEY in the request header
        '429':
          description: Too Many Requests. Rate limit is 20 requests/sec and 400 requests/min
        '500':
          description: Internal Server Error
components:
  schemas:
    RejectReason:
      type: object
      properties:
        Id:
          type: integer
          description: Track-POD unique identifier
          format: int32
          example: 2
        Name:
          type:
          - string
          - 'null'
          description: Name
          example: Canceled
      additionalProperties: false
      xml:
        name: RejectReason
    RejectReasonsList:
      type: object
      properties:
        SiteIssue:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/RejectReason'
          description: List of site issues
          xml:
            name: SiteIssue
            wrapped: true
        OrderIssue:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/RejectReason'
          description: List of order issues
          xml:
            name: OrderIssue
            wrapped: true
        GoodsIssue:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/RejectReason'
          description: List of goods issues
          xml:
            name: GoodsIssue
            wrapped: true
        ScanningIssues:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/RejectReason'
          description: List of scanning issues
          xml:
            name: ScanningIssues
            wrapped: true
      additionalProperties: false
      xml:
        name: RejectReasonsList
  securitySchemes:
    ApiKey:
      type: apiKey
      description: Please enter API key into field
      name: X-API-KEY
      in: header
