openapi: 3.2.0
info:
  title: Track-POD Test API
  description: Track-POD API enables ERP or any other system integration with Track-POD without need for any manual data input.
  version: '2.0'
security:
- ApiKey: []
tags:
- name: Test
paths:
  /Test:
    get:
      tags:
      - Test
      summary: Test authorization and rate limits
      operationId: Test
      responses:
        '200':
          description: Return string "ok" on successful response
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
            text/xml:
              schema:
                type: string
        '401':
          description: Unauthorized. Invalid X-API-KEY in the request header
        '415':
          description: Unsupported Media Type. Invalid Content-Type in the request header. Must be application/json or application/xml
        '429':
          description: Too Many Requests. Rate limit is 20 requests/sec and 400 requests/min
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      description: Please enter API key into field
      name: X-API-KEY
      in: header
