openapi: 3.2.0
info:
  title: Track-POD Vehicle Check API
  description: Track-POD API enables ERP or any other system integration with Track-POD without need for any manual data input.
  version: '2.0'
security:
- ApiKey: []
tags:
- name: VehicleCheck
paths:
  /VehicleCheck/{number}:
    get:
      tags:
      - VehicleCheck
      summary: Get last vehicle check by number
      operationId: GetCheckByVehicle
      parameters:
      - name: number
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Vehicle check
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/VehicleCheck'
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleCheck'
            text/json:
              schema:
                $ref: '#/components/schemas/VehicleCheck'
            application/xml:
              schema:
                $ref: '#/components/schemas/VehicleCheck'
            text/xml:
              schema:
                $ref: '#/components/schemas/VehicleCheck'
        '401':
          description: Unauthorized. Invalid X-API-KEY in the request header
        '429':
          description: Too Many Requests. Rate limit is 20 requests/sec and 400 requests/min
        '500':
          description: Internal Server Error
  /VehicleCheck/Number/{number}/Date/{date}:
    get:
      tags:
      - VehicleCheck
      summary: Get vehicle checks by date
      operationId: GetChecksByVehicle
      parameters:
      - name: number
        in: path
        required: true
        schema:
          type: string
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Vehicle checks
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            text/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
        '401':
          description: Unauthorized. Invalid X-API-KEY in the request header
        '429':
          description: Too Many Requests. Rate limit is 20 requests/sec and 400 requests/min
        '500':
          description: Internal Server Error
  /VehicleCheck/Date/{date}:
    get:
      tags:
      - VehicleCheck
      summary: Get vehicle checks by date
      operationId: GetVehicleChecksByDate
      parameters:
      - name: date
        in: path
        required: true
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Vehicle checks
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
            text/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VehicleCheck'
                xml:
                  name: List`1
        '401':
          description: Unauthorized. Invalid X-API-KEY in the request header
        '429':
          description: Too Many Requests. Rate limit is 20 requests/sec and 400 requests/min
        '500':
          description: Internal Server Error
components:
  schemas:
    VehicleCheck:
      type: object
      properties:
        DriverLogin:
          type:
          - string
          - 'null'
          description: Driver's login
          example: 'RT567 '
        DriverName:
          type:
          - string
          - 'null'
          description: Driver’s First Name and Last Name
          example: Peter G.
        DepotId:
          type:
          - string
          - 'null'
          description: Unique identifier in user accounting system
          example: 1
        Depot:
          type:
          - string
          - 'null'
          description: Depot address
          example: '9 Riverside, Salford M7 1PA '
        Date:
          type: string
          format: date-time
        VehicleNumber:
          type:
          - string
          - 'null'
          description: Vehicle number
          example: XXX777
        Odometer:
          type:
          - number
          - 'null'
          description: Odometer
          format: double
        Values:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/VehicleCheckValue'
          description: Vehicle check values
          xml:
            name: Values
            wrapped: true
        HasSignature:
          type: boolean
          description: Signature attached
          example: true
        SignaturePhoto:
          type:
          - string
          - 'null'
          description: Links for download jpg file (each link is available for 24h from API call)
        Stage:
          $ref: '#/components/schemas/VehicleCheckStage'
        RouteNumber:
          type:
          - string
          - 'null'
      additionalProperties: false
      xml:
        name: VehicleCheck
    VehicleCheckValue:
      type: object
      properties:
        Label:
          type:
          - string
          - 'null'
          description: Vehicle check label
          example: Tyre and Wheel Nuts
        Status:
          type:
          - boolean
          - 'null'
          description: Check status
        Photo:
          type:
          - boolean
          - 'null'
          description: Photo attached
        Photos:
          type:
          - array
          - 'null'
          items:
            type: string
          description: Array of links for download jpg file (each link is available for 24h from API call)
          xml:
            name: Photos
          example:
          - https://image.track-pod.com/...
        Note:
          type:
          - string
          - 'null'
          description: Note
        Value:
          type:
          - number
          - 'null'
          description: Value
          format: double
      additionalProperties: false
      xml:
        name: VehicleCheckValue
    VehicleCheckStage:
      enum:
      - BeforeRoute
      - AfterRoute
      type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      description: Please enter API key into field
      name: X-API-KEY
      in: header
