openapi: 3.0.4
info:
  title: Track-POD Address Test API
  description: 'Track-POD API enables ERP or any other system integration with Track-POD without need for any manual data input. Our API provides an easy HTTP interface to Track-POD functionality through JSON or XML<br><br><b>Endpoint:</b><br>https://api.track-pod.com/<br><br><b>Request headers:</b><br><b>X-API-KEY</b> - API Key. Please find the API key in the Track-POD settings <br><b>Content-Type</b> - (POST/PUT) Request input type: <b>application/json</b> - JSON, <b>application/xml</b> - XML<br><b>Accept</b> - Response output type: <b>application/json</b> - JSON, <b>application/xml</b> - XML <br><b>Accept-Encoding</b> - Response compression: <b>gzip, deflate, br</b><br><br><b>Webhooks:</b><br>Create/Update/Delete route, Create/Update/Delete order, and more <a target=''_blank'' href=''https://track-pod.freshdesk.com/support/solutions/articles/103000049842''>How to use Webhooks?</a>'
  version: '2.0'
security:
- ApiKey: []
tags:
- name: Test
paths:
  /Test:
    get:
      tags:
      - Test
      summary: Test authorization and rate limits
      operationId: Test
      responses:
        '200':
          description: Return string "ok" on successful response
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
            text/xml:
              schema:
                type: string
        '401':
          description: Unauthorized. Invalid X-API-KEY in the request header
        '415':
          description: Unsupported Media Type. Invalid Content-Type in the request header. Must be application/json or application/xml
        '429':
          description: Too Many Requests. Rate limit is 20 requests/sec and 400 requests/min
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      description: Please enter API key into field
      name: X-API-KEY
      in: header
